name: Elkarbackup
description: |
  Open source backup solution for your network
version: v1.3.1
category: Security
maintainer: Xabi Ezpeleta <xezpeleta@gmail.com>
license: New-BSD
projectURL: https://www.elkarbackup.org
